language: node_js
node_js:
- 5.6.0
- 4.3.1
notifications:
  email:
    on_success: change
    on_failure: always
cache:
  directories:
  - node_modules
before_install:
- npm install -g npm@3.7.2
after_script:
- npm run coverage
- "./node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info"
env:
  global:
    secure: eTl68A32kNfZ+yDyKe/2rMdfTyNXWksz2bhJEV8pnBEc3LjLjY97KYAW8rICmVyg21fdOwXzm0adoNzj5hIin/Q72ISJFACsWy18MDfr68pHBweNQ8FGbuTzMhQgxLGr5IKFmDfysET/KLXZvED22w99F8SQ2cw59zrqJKB+iLIafbBabTShhwqVH5JmuGxqPgetZNuw24qWirHfHRgCaXm4Mq6YBKPgLwAWb4yCh4FRPP1Y6nxQ9E71fRwWHkD1wXOh3YcacvrF8WtNHeE415GxsNLhEK3iiwjhqLyre7IA6C3XPYTQasWtPygKIMk4UMevnQM3NgKBs2u62fZxNwsgoM6aKtIfUkDMVUx+Mvwk8rbRuVX+jcoO16A2ZktOpdEQ6BMoZWQlBx1AU2YwpL4Zqy+ChgAIf/dQfwi/jSm4ENC4CNz1Z5D4eY83aX2nQwwhoVVkThmL8JIpNhn8a1ZmgzmlgTiW/pj+qF8pJYUDJ7t8Mi1qhqZwSIBG1U/291can3cPo1WKzNZ7dPUYz0GP8w9PebJh/erJDyOe0PFMHkJ2jw/6Ep0QZTTvRb3GqeB9rGLQoiuybZ8Vruzykv2cyVtFmovaS4xVP+KD0R8Ya6SX0/TerEUz/6BU4L8+cmpXt1+2Nudgux1cip1jE4d1Ha+R97diZ8Mxwfw2rkk=
