language: node_js
node_js:
- '6'
- 6.3.0
- '4'
- 4.4.7
notifications:
  email:
    on_success: change
    on_failure: always
cache:
  directories:
  - node_modules
before_install:
- npm install -g npm@3.10.3
after_script:
- npm run coverage
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- "./node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info"
env:
  global:
  - secure: sJmeZgGvd7xsuM0iUfSUVAXg0Uqc13t0HTswJMnTSqfU4ZE2cgfKT0AVLoHWRYay267gMVcvpcn+bwjut9kZOmHQb2PvPThuyko7jsWd/j78zcp2Y4eLePNUsJPeAoxURJ2OReIH1kNrbqtTywvX3gsbQPS06c8Pc/6Ri3aXxPPqsgPy6f832BKJRH66x2KJtBbcIcTuofa3hejcoy2wO3DhjCe+OGWftbLxN/1oWKSJ5Bpq7OwQpFNtgReyJf1h4L/lSKA7cugMYyT0z9tMrwxBss/1hT+ElWmcxb+7PNKG391SIRYHC0XoBVqwC0pC4N11UpICvklmaTBdbwRhJj4fVSwwHP7P6JroigOehBcopqn8mEwB+UVmO+EwNopDWwsZY7IgTsZHiYGdLAlz3svcbLfS0yM9XB+sU5vL4uLuu514XqT9UIwP9atVQkPH7+J4V+yr3sx5qf/fvo2ZPDh4aixAfvg2D0xgTX90d7QiLaDoitaeH4UmcNqehUnsAyjYt0p0R4Egevamy8SxIA7HLBQARwSYXzemhHqyUsXXJcJyIYBxZezydnwD+mIebVEhyDH3w9co33OSaPxAlzDhL9Ohq9qXRxSc+fjGlMF5Uns1MWNdHuGWfKlVsdvgtXE9Snu8f2deCtfvFK2TeaFLFK+A0VJIwYOjQLzVpQA=
  - secure: sM+nF9qj7SpvM2n70v7ncgWj8wTl2okBX8qJJn0dQdNbkY/joNsL694P5lXmV7q9wI9o4GZ6Iz/xvorjR3hFq3FPXB70nn4Cc7Bq1zsfTcK2KgPw4jFQvFAj0u1d5OXjzAGrPKHa6JZ+kqt7jmuK9LjzbaCiq64BLKVraLFVpNph/dCXSRz+mhIyg6O6FjesxAIK+6v1CcS61Qmq1sjVQSg+9ujetj3uq1A8b7buJw9ta7l3qKst5vFIQp0Lqjj37AE45A+Ck5BMnhcSiH5mm8LAusgChW8QzcHFbbrlX/u9AoxLq5MpeILJKII/C4GoZJtRd253YVjML46mLzmrY+8N575PycF8HfrOzXKDplO/asAD+D/d+tYI1T+IzVqipYFyAp4RdjpZEVC5w8u5lD7mmhdDK8oR1mwNv3vET4v9ioHA4dpO4zGBNsVCiKuZqFhavnUM0JprjxpFBcMQkJjU7e8I4IweiSOaZ9gA3BzXmb2MfTSkNBqT1soVBjSHlCyIN6TyG9vTz8x2t+0uoVYwZg8NlMkjWL9+eWqwP6cHUsLeu0PJ99t1CWoyKBGNLb1eOecIjiwZUjIf3Zn5GbyoHobNLrbaHqC1Y+9/lWSsxbxyzCI3S0toZ5frehG+zIGmpTLZkjdQvzEfi9nhlhPgdeGstb1SftJ7NexG0bI=
