language: node_js
node_js:
- '8'
- '6'
notifications:
  email:
    on_success: change
    on_failure: always
before_install:
- npm install -g greenkeeper-lockfile@1
before_script:
- greenkeeper-lockfile-update
after_script:
- greenkeeper-lockfile-upload
- npm run coverage
- npm run codeclimate
env:
  global:
  - secure: cSEX/h/CtCB1bWROheybbmM/xSwtQ13g5bjrevavgNoH8NGrTw0tGS3QFFmNQyTlB67/SOL17fBYuZfjl4fW30EuwCpecQnMSx02T8t9LL/f7f/i1bZYPUzCl/U/3GroAwlam1Pig8tYTScKrjfd8A5jtTNqvSA/XYI60a8fnl2XXL3MT0Rf4KYZnuEzldMmUxnoC1GPX/RCRXSiehBboj02xCybuBm0Ll8rFdOugycOBO/ph8si1T35zVYBGVSRrIyDchutRJdjS4doUxQ2VHunM+Rt7ASWVmvm9/Ab/rGgJbGqKVxNm6rnzBz0e0FvUHBGjWDHLSp8hQsPiS5aCE8vwnGS+MVkG4+ZKxUym4IObHgUVbfxKqLd6vtC2iggCORU9txI2yXHZOIYtIyh2QphjjJFCtD2S/uUqCmjxHupWQFg09SuEgTOhMFftxeulaZgefaIxNhRyxs0jyFPZ4o55UJyTSgajtMFr6eyinjFi6iG+Mz0oCpnVFzxyUOG2n8GiDGqDBeHOSzD2ZT/LFazLxVNj1PTkH3AKw09H8Cw1/SySo0d69DsZhaxX7xFZQPqzlmkT/lpIBGHoMoGB3WAJh/eNAYvt+FPNvgtzSl3+DLO9aMdzwy5RUZvK6z3HCjqHEIQQfo7NIEmX/zwZyL6/nt7S+WaqGVihbWDuTU=
  - secure: iFI3wLDff1ZfYiEazKoivF2/R9x9V64qcAJYLBN4ulAJgC1uyrxuM59R+MtPmCLo89TZEK94RIcrOTg4snz2KWEgpXObi79wZwWR4QC/jPL6pEu4FGkMZU8ANExDD09KGPaFjcCKOIdHH7P84nhaSNgANPvTKBHapV8sJLctzE3UCobXGkwOFAhWIpuQsm9OPP/FQFUoUderaKTHBmv6ys1kedykk2UnlCD72ldITOC6kLR9kbfSx2ELjLOEK3+R7shVF0tbjj4KZrtol63CP145bocLaaCLQG98nI2Hj/edc439z4DMkz8A24No/mgW85Zyx4ceL5ofsarGnZ6OS1H6YwGzhAAjO4sgnlPHiGygYSwqTE1qDfUMdkbm/Gh+mrEFHIcgwkt5yLXUN96V30QJiJNq72i8FhjaWBihDjCPFcNZAI0xx4No5lZnOklTZCRknLqc76lunLKNiqhkRLXMgKCM1fwDi0CSw1V2kSX2BiTRikPvdInH2G87DJxZLdMzn72/FzkSusvr66sEZ2iNlgwLFAzVv5BVLtQUUKzrZGt8xLsWtxJu/GXkJ8Nqm2hwL0ypbqLty+zHzPfXy1OCIOWtAKdq1/dujhHaeepVXWBGfq7q4FSq8gCXmSc0E3Jxo62fxSIuq37fAETU9UDj88ibGD0pxqwbObS/xBk=
